<%
Const SIAP_DATABASE_PATH = "SIAP_ORACLE"
Const SIAP_DATABASE_NAME = "SIAP"
Const SIAP_DATABASE_USERNAME = "SIAP"
Const SIAP_DATABASE_PASSWORD = "SiapOracle"
Const SIAP_PREFIX = ""

'Const SIAP_DATABASE_PATH = "SIAP_SQL_DSN"
'Const SIAP_DATABASE_NAME = "SIAP_SQL"
'Const SIAP_DATABASE_USERNAME = ""
'Const SIAP_DATABASE_PASSWORD = ""
'Const SIAP_PREFIX = ""

Const SADE_DATABASE_PATH = "SIAP_ORACLE"
Const SADE_DATABASE_NAME = "SIAP"
Const SADE_DATABASE_USERNAME = "SIAP"
Const SADE_DATABASE_PASSWORD = "SiapOracle"
Const SADE_PREFIX = "SADE_"
Const SADE_COURSE_ID = 171
Const SADE_GROUP_ID = 13
Const SADE_PROFILE_ID = 4

Const TACO_DATABASE_PATH = "SIAP_ORACLE"
Const TACO_DATABASE_NAME = "SIAP"
Const TACO_DATABASE_USERNAME = "SIAP"
Const TACO_DATABASE_PASSWORD = "SiapOracle"
Const TACO_PREFIX = "TACO_"

Const EMAIL_SERVER = "issste.gob.mx"
Const S_EXCLUDED_TABLES = ",Preferences,PaperworkOwnersLKP"
Const S_TABLES_FOR_AUDIT = ",Areas,Employees,"

Const S_FLASH_PLAYER_URL = "http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0"

'GUI
Const S_MAIN_COLOR_FOR_GUI = "757575"
Const S_MAIN2_COLOR_FOR_GUI = "555555"
Const S_LIGHT_BGCOLOR = "FFFFFF"
Const S_DARK_BGCOLOR = "FFFFFF"
Const S_SELECTED_BGCOLOR = "757575"

'LINKS
Const S_SELECTED_LINK_FOR_GUI = "999999"
Const S_MENU_LINK_FOR_GUI = "FFFFFF"
Const S_SUBMENU_LINK_FOR_GUI = "FFFFFF"

'MENU
Const S_BORDER_MENU = "004795"
Const S_LIGHT_BGCOLOR_MENU = "333333"
Const S_DARK_BGCOLOR_MENU = "001462"
Const S_SELECTED_BGCOLOR_MENU = "CCCCFF"

'TABLES
Const S_LIGHT_BGCOLOR_FOR_GUI = "CCCCFF"
Const S_BGCOLOR_FOR_GUI = "3c3c3c"
Const S_DARK_BGCOLOR_FOR_GUI = "353535"
Const S_BANDING1_FOR_GUI = "EEEEEE"
Const S_BANDING2_FOR_GUI = "DDDDDD"

'TEXT
Const S_INSTRUCTIONS_FOR_GUI = "004795"
Const S_WARNING_FOR_GUI = "D20000"
Const S_CONFIRMATION_FOR_GUI = "004795"
Const S_INACTIVE_TEXT_FOR_GUI = "999999"

'TITLES
Const S_TABLE_TITLE_FOR_GUI = "FFFFFF"
Const S_MAIN_TITLE_FOR_GUI = "6b6b6b"
Const S_SECOND_TITLE_FOR_GUI = "D20000"

'WIDGET
Const S_WIDGET_FRAME_FOR_GUI = "555555"
Const S_WIDGET_BGCOLOR_FOR_GUI = "CCCCFF"
Const S_WIDGET_SECOND_BGCOLOR_FOR_GUI = "8899AA"
Const S_WIDGET_LIGHT_FOR_GUI = "99FF99"

'TABS
Const S_TAB_BGCOLOR_FOR_GUI = "004795"
Const S_TAB_TEXT_FOR_GUI = "FFFFFF"

'WIZARD
Const S_WIZARD_TITLE_FOR_GUI = "004795"

'MISCELANEOUS
Const S_ADMIN_EMAIL_ACCOUNT = "vic_arjona@yahoo.com"
%>